
NAME: CARSN-BN-MemoryContrastiveLossPRISM-sTRM

MODEL:
  BACKBONE:
    NAME: bninception
    FREEZE_BN: False
  HEAD:
    DIM: 512
    IN_CHANNELS: 1024

LOSSES:
  NAME: 'memory_contrastive_loss_w_PRISM'

INPUT:
  MODE: RGB
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]


SOLVER:
  MAX_ITERS: 4000 
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003 
  WEIGHT_DECAY: 0.0005 
  LR_SCHEDULAR: 'cos'
TB_SAVE_DIR: CARSNruns
DATA:
  TRAIN_IMG_SOURCE: 'datalist/CARSN_train.csv'
  TEST_IMG_SOURCE: 'datalist/CARSN_test.csv'
  TRAIN_BATCHSIZE: 64
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 16
  NUM_INSTANCES: 4

VALIDATION:
  VERBOSE: 100
XBM:
  ENABLE: True
  WEIGHT: 1.0
  SIZE: 9500
  START_ITERATION: 0
NOISE:
  NOISE_RATE: 0.5
  WINDOW_SIZE: 30
  CHECK_NOISE: False